services:
  db:
    image: postgres:16
    container_name: asset-depre-db-1
    environment:
      POSTGRES_DB: sankyu_assets
      POSTGRES_USER: sankyu
      POSTGRES_PASSWORD: sankyu123
    ports:
      - "5436:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
